# Generated by Django 4.1.2 on 2022-11-28 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_url', models.CharField(default='https://firebasestorage.googleapis.com/v0/b/fiction-fans.appspot.com/o/no-cover.png?alt=media&token=007d2b16-2e97-409b-b5ed-c3729fa5dc3a', max_length=255)),
                ('author', models.CharField(default='Anonymous', max_length=255)),
                ('status', models.CharField(choices=[('Oneshot', 'Oneshot'), ('Ongoing', 'Ongoing'), ('Finish', 'Finish'), ('Drop', 'Drop')], default='Ongoing', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FictionChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_editorjs.fields.EditorJsField()),
                ('fiction_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiction_fans.fictiontitle')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiction_fans.fictionchapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
