# Generated by Django 4.1.2 on 2022-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fictiontitle',
            name='translator',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='fictiontitle',
            name='status',
            field=models.CharField(choices=[('Oneshot', 'Oneshot'), ('Ongoing', 'Ongoing'), ('Finish', 'Finish'), ('Draft', 'Draft'), ('Drop', 'Drop')], default='Ongoing', max_length=255),
        ),
    ]
