# Generated by Django 4.1.1 on 2022-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fictiontitle',
            name='cover',
            field=models.ImageField(blank=True, default='/static/images/no-cover.png', null=True, upload_to=''),
        ),
    ]
