# Generated by Django 4.1.1 on 2022-11-02 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
