# Generated by Django 4.1.1 on 2022-11-05 12:07

from django.db import migrations, models
import django.db.models.deletion
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0002_story_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FictionChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_editorjs.fields.EditorJsField()),
            ],
        ),
        migrations.CreateModel(
            name='FictionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.AddField(
            model_name='fictionchapter',
            name='novel_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiction_fans.fictiontitle'),
        ),
    ]
