# Generated by Django 4.1.1 on 2022-11-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0002_ratemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratemodel',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fiction_fans.fictionchapter'),
            preserve_default=False,
        ),
    ]
