# Generated by Django 4.1.2 on 2022-11-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0002_fictiontitle_translator_alter_fictiontitle_status'),
        ('fiction_fans', '0003_ratemodel_chapter'),
    ]

    operations = [
    ]
