# Generated by Django 4.1.1 on 2022-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0003_remove_fictiontitle_cover_fictiontitle_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fictiontitle',
            name='cover_url',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/fiction-fans.appspot.com/o/no-cover.png?alt=media&token=007d2b16-2e97-409b-b5ed-c3729fa5dc3a', max_length=255),
        ),
    ]
