# Generated by Django 4.1.1 on 2022-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0004_merge_20221129_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='fictiontitle',
            name='cover_pic_name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
