# Generated by Django 4.1.1 on 2022-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiction_fans', '0004_alter_fictiontitle_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fictiontitle',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='fictiontitle',
            name='cover',
            field=models.ImageField(default='https://firebasestorage.googleapis.com/v0/b/fiction-fans.appspot.com/o/no-cover.png?alt=media&token=007d2b16-2e97-409b-b5ed-c3729fa5dc3a', upload_to=''),
        ),
    ]
